Update to 1.20.1
juancarloscp52/Entropy pull request #122
Opened 2023-07-14 14:46 UTC by bl4ckscor3

This is a port of the mod to Minecraft 1.20.1. I also updated JDA to 5.0.0-beta.12, which meant having to rewrite a bit of that code. I tested the changes and Discord integration still works fine. One other change that is unrelated to the version port is removing the `votingClient` field from `MinecraftUIRenderer`, as it was unused.
I've done a small bit of testing, and the mod looks to be working fine.

Note, that due to the lack of a 1.20.1 branch, I am PRing this to 1.19.4 - but the branch should ideally be changed before merging.

2023-10-19 01:45 UTC, JeremyStarTM commented
+1

2025-02-26 20:42 UTC, slicedlime requested changes
Looks mostly good! Bunch of small comments, only real problem I spotted is throwing call in discord integration.

2025-02-26 20:42 UTC, slicedlime commented on gradle.properties
> +loader_version=0.14.21
These aren't the latest. Not sure if it matters enough to care.

```
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.10
```

2025-02-26 20:42 UTC, slicedlime commented on gradle.properties
> +fabric_version=0.85.0+1.20.1
This definitely seems worthwhile to have at latest
`fabric_version=0.92.3+1.20.1`

2025-02-26 20:42 UTC, slicedlime commented on src/main/java/me/juancarloscp52/entropy/client/Screens/EntropyIntegrationsScreen.java
> +                                    default -> "entropy.options.integrations.youtube.help"; }))).build());
Nit: Probably shouldn't reformat unrelated code - at least unless we set a decided code styling.

2025-02-26 20:42 UTC, slicedlime commented on src/main/java/me/juancarloscp52/entropy/client/VotingClient.java
> +        drawContext.fill( 10, 31 + (i * 18), pollWidth+45+ 10 , 35 + (i * 18) + 10, ColorHelper.Argb.getArgb(150,0, 0, 0));
Nit: Leading spaces in method argument lists in this method

2025-02-26 20:42 UTC, slicedlime commented on src/main/java/me/juancarloscp52/entropy/client/integrations/discord/DiscordEventListener.java
> +            emojisToRemove.add(Emoji.fromUnicode("4️⃣"));
Could be written a bit more compactly:
```suggestion
            Stream.of("1️⃣", "2️⃣", "3️⃣", "4️⃣").map(Emoji::fromUnicode).forEach(emojisToRemove::add);
```

2025-02-26 20:42 UTC, slicedlime commented on src/main/java/me/juancarloscp52/entropy/client/integrations/discord/DiscordEventListener.java
> +            switch (event.getReaction().getEmoji().asUnicode().getName()){
This seems to throw if anyone reacts with a non-unicode reaction

2025-02-26 20:42 UTC, slicedlime commented on src/main/java/me/juancarloscp52/entropy/events/db/AngryBeeEvent.java
> +                );
A number of these in the PR. Worth pulling this up to the previous line if they all get poked anyway?

2025-02-26 21:22 UTC, bl4ckscor3 commented on gradle.properties
> +fabric_version=0.85.0+1.20.1
Updating to that version requires a newer Loom version, so I'll go ahead and update all of that, too. Since this PR already contains build file changes, it's probably fine to do.

2025-02-26 21:30 UTC, bl4ckscor3 commented on src/main/java/me/juancarloscp52/entropy/events/db/AngryBeeEvent.java
> +                );
Just gonna revert for now since it's a code-style thing anyway.

2025-02-26 21:31 UTC, bl4ckscor3 commented on src/main/java/me/juancarloscp52/entropy/events/db/AngryBeeEvent.java
> +                );
Just gonna revert, as it's a code-style thing anyway.

2025-02-27 06:04 UTC, slicedlime approved these changes

2025-02-27 10:00 UTC, merged